networks:
  internal-net:

volumes:
  clickhouse_data:
  clickhouse_logs:

services:
  # ----------------------------------------------------------------------------
  # jupyter
  # ----------------------------------------------------------------------------
  service.jupyter:
    build:
      context: .
      dockerfile: ./services/jupyter/Dockerfile
    ports:
      - 8888:8888      
    volumes:
      - ./services/jupyter/notebooks:/home/jovyan/work/notebooks
      - ./db:/home/jovyan/work/db
    restart: unless-stopped
    networks:
      - internal-net

  # ----------------------------------------------------------------------------
  # apache superset
  # ----------------------------------------------------------------------------
  service.superset:
    build:
      context: .
      dockerfile: ./services/superset/Dockerfile
    ports:
      - 8088:8088
    volumes:
      - ./services/superset/data:/app/superset_home
      - ./db:/app/database
    restart: unless-stopped
    networks:
      - internal-net
 
  # ----------------------------------------------------------------------------
  # database
  # ----------------------------------------------------------------------------
  service.db_postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./services/postgres/db:/var/lib/postgresql/18/docker
    env_file:
      - ./services/postgres/.env
    restart: unless-stopped
    networks:
      - internal-net


  # ----------------------------------------------------------------------------
  # database
  # ----------------------------------------------------------------------------
  service.db_clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
    env_file:
      - ./services/clickhouse/.env
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server   
    restart: unless-stopped
    networks:
      - internal-net      
  # service.db_clickhouse:
  #   # build:
  #   #   context: .
  #   #   dockerfile: ./services/clickhouse/Dockerfile
  #   image: clickhouse/clickhouse-server:latest
  #   ports:
  #     - 8123:8123
  #     - 9000:9000
  #   # ulimits:
  #   #   nofile:
  #   #     soft: 262144
  #   #     hard: 262144   
  #   # cap_add:
  #   #   - SYS_NICE
  #   #   - IPC_LOCK
  #   # volumes:
  #   #   - ./services/clickhouse/data/db:/var/lib/clickhouse:rw
  #   #   - ./services/clickhouse/data/log:/var/log/clickhouse-server:rw
  
